version: "3.4"

services:
  reachservice:
    image: reachservice
    container_name: reachservice
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo.docker:27017
      ONEAUTH_API: https://api.ioak.io:8010/api
      PORT: 8045
    ports:
      - 8045:8045
    networks:
      ioak-net:
        aliases:
          - reachservice.docker

networks:
  ioak-net:
    name: ioak-network
